name = "ELEC2117_Project"
uuid = "89f6aaa3-436f-4694-b786-58ba87b77b8f"
authors = ["Hazzoz <hwils2019@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
